/*

  Includes:

  Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(h){var j,d;d={_breaker:{},each:function(a,c){var i,b;if("object"===d.type(a)&&a.hasOwnProperty)for(i in a){if(a.hasOwnProperty(i)&&c(a[i],i)===d._breaker)break}else{i=0;for(b=a.length;i<b&&c(a[i],i)!==d._breaker;i++);}},extend:function(a){var c,i,b,d,o=arguments.length;a=a||{};for(i=1;i<o;i++)if(d=arguments[i],void 0!==d&&null!==d)for(b in d)c=d[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(a){return null===a?"null":void 0===a?"undefined":("object"===typeof HTMLElement?
a instanceof HTMLElement:a&&"object"===typeof a&&null!==a&&1===a.nodeType&&"string"===typeof a.nodeName)?"element":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}};d.extend(d,{addClass:function(a,c){d.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},attrValues:function(a,c,i){return(c=a[c])?c.split(i||" "):[]},bind:function(a,c){return function(){return a.apply(c,arguments)}},browser:function(){var a={},c,i=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,
"$1; ").replace(/\;\s*$/,"").split(/;\s*/);d.each(i,function(i){c=(/[\/ :]([^\/ :]+)$/.exec(i)||[])[1];a[c?i.substr(0,i.length-c.length-1).replace(/\d*$/,""):i]=c||!0});return{aol:a.aol,blackberry:a.blackberry,ie:a.msie,ios:a.mobile&&a.safari,opera:a.opera,playstation:a.playstation,version:parseFloat(a.version||a.crios)||!1}}(),cache:function(){var a={},c="vglnk_"+(new Date).getTime(),i=0;return function(b,d,o){if(b){var m=b[c];if(m||void 0!==o)return m||(m=++i),a[m]||(b[c]=m,a[m]={}),void 0!==o&&
(a[m][d]=o),"string"===typeof d?a[m][d]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=d.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return d.extend({},a)},contains:function(a,c){return-1!==d.indexOf(a,c)},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a){for(var c=window.self;c.parent&&c.parent!==c;)if(c=c.parent,c===
a)return!0;return!1},cors:function(a){var c,i=function(){eval(c.responseText)};c=new window.XMLHttpRequest;c.onreadystatechange=function(){4===c.readyState&&200===c.status&&i()};try{c.open("GET",a),c.withCredentials=!0,c.send()}catch(b){return!1}},createA:function(a,c){return d.createEl("a",{href:a,target:c})},createEl:function(a,c,i,b){var f;a=(b||document).createElement(a);c=c||{};i=i||{};for(f in c)void 0!==c[f]&&(a[f]=c[f]);d.css(a,i);return a},css:function(a,c){for(var i in c)try{a.style[i]=
c[i]}catch(b){}return a},destructing:function(a){var c=!1,i;return function(){c||(i=a.apply(null,arguments),c=!0);return i}},escapeRegExp:function(){var a;return function(c){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,i=a.target||a.srcElement;do{try{c=i.nodeType}catch(b){break}if(1===c&&(a=i.tagName.toUpperCase(),"A"===a||"AREA"===a))return i;i=i.parentNode}while(i)},exceptionLogger:function(){var a=!1,c=d.noop;return function(i,b){if(void 0!==
b)a=b,c=i;else return function(){if(a)try{return i.apply(this,arguments)}catch(b){c(b)}else return i.apply(this,arguments)}}}(),find:function(a,c){var i;d.each(a,function(a,b){if(c(a,b))return i=a,d._breaker});return i},generateNodeFilter:function(){var a=function(a,c){var b,d;c=","+c.join(",")+",";b=0;for(d=a.length;b<d;b++)if(-1!==c.indexOf(","+a[b]+","))return!0;return!1},c=function(a,c){var b=a.nodeName.toLowerCase();return-1!==c.indexOf(","+b+",")};return function(i){i=d.extend({custom:null,
classes:[],rels:[],tags:[]},i);i.tags.length&&(i.tags=","+i.tags.join(",").toLowerCase()+",");return function(b,f){f=d.extend({ancestors:!0,self:!0},f);var o=!0,m=!0,e=function(b,g){var f;if(f=!(i.tags.length&&c(b,i.tags))){if(f=i.classes.length){f=i.classes;var o=d.attrValues(b,"className");f=a(f,o)}if(f=!f){if(f=i.rels.length)f=i.rels,o=d.attrValues(b,"rel"),f=c(b,",a,")&&a(f,o);f=!f&&!("function"===d.type(i.custom)&&i.custom(b,g))}}return f},m=!f.self||e(b,!0);if(f.ancestors)for(;b.parentNode;)if(b=
b.parentNode,1===b.nodeType&&!e(b,!1)){o=!1;break}return m&&o}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("\x26");var c={};d.each(a,function(a){a=a.split("\x3d");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,i=Infinity,b=Infinity,f=-Infinity,o=-Infinity,m;for(a=0;a<c;a++)m=d.position(arguments[a]),i=Math.min(i,m.x),b=Math.min(b,m.y),f=Math.max(f,m.x+arguments[a].offsetWidth),o=Math.max(o,m.y+arguments[a].offsetHeight);
return{x:i,y:b,w:f-i,h:o-b,x1:i,y1:b,x2:f,y2:o}},getActualHref:function(a){return d.cache(a,"href")||a.href},hasAttrValue:function(a,c,i,b){return c?d.contains(d.attrValues(a,c,b),i):!1},hasClass:function(a,c){return d.hasAttrValue(a,"className",c)},hasRel:function(a,c){return d.hasAttrValue(a,"rel",c)},indexOf:Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c)}:function(a,c){var i,b;i=0;for(b=a.length;i<b;i++)if(a[i]===c)return i;return-1},isArray:function(a){return"array"===
d.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=d.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var i=[];d.each(a,function(a,b){void 0!==a&&(i[b]=c(a))});return i},on:function(){var a;return function(c,i,b){var f,o;if(1===arguments.length)a=c;else{if(2===arguments.length){if(!a)return;
b=i;i=c;c=a}try{f=c["on"+i]}catch(m){}"function"===typeof f&&(c["on"+i]=d.bind(function(a){a=a||window.event;var b=f.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==b&&!1!==a.returnValue&&(a.returnValue=b),d.isDefaultPrevented(a)&&"function"===d.type(a.preventDefault)&&a.preventDefault(),a.returnValue):b})()},this));o=d.exceptionLogger(function(){if(a.enabled())return b.apply(null,arguments)});c.addEventListener?c.addEventListener(i,o,!1):c.attachEvent&&c.attachEvent("on"+i,
o)}}}(),position:function(a){var c,b=0,d=0,f=0,o=0;if(!a.offsetParent)return!1;c=a;do b+=c.offsetLeft,d+=c.offsetTop,c=c.offsetParent;while(c);c=a;do f+=c.scrollLeft,o+=c.scrollTop,c=c.parentNode;while(c&&c!==document.body);return{x:b-f,y:d-o}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,c=[],b=!1,g,f,o,m,e;document.addEventListener?o=function(){document.removeEventListener("DOMContentLoaded",o,!1);e()}:document.attachEvent&&(m=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),e())});g=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return e();if(document.addEventListener)document.addEventListener("DOMContentLoaded",o,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(b){}document.documentElement.doScroll&&c&&f()}d.on(window,"load",e)}};f=function(){if(!b){try{document.documentElement.doScroll("left")}catch(a){setTimeout(d.exceptionLogger(f),
1);return}e()}};e=function(){if(!b){if(!document.body)return setTimeout(d.exceptionLogger(e),13);b=!0;c&&(d.each(c,function(a){a()}),c=null)}};return function(a){g();b?a():c.push(a)}}(),reformatKeys:function(a){var c,b,g=function(a){return"_"+a.toLowerCase()};for(c in a)b=c.replace(/([A-Z])/g,g),"object"===d.type(a[c])&&(a[c]=d.reformatKeys(a[c])),b!==c&&(a[b]=a[c],delete a[c]);return a},removeClass:function(a,c){if(d.hasClass(a,c)){var b,g,f=d.attrValues(a,"className");b=0;for(g=f.length;b<g;b++)f[b]===
c&&delete f[b];a.className=f.join(" ")}},request:function(a,c,b){var g,f;b=d.extend({fn:d.noop,"return":!1,timeout:null},b);"string"===typeof b.fn?c=d.extend(c,{jsonp:b.fn}):"function"===typeof b.fn&&(g=d.destructing(b.fn),f=d.uniqid("vglnk_jsonp_"),c=d.extend(c,{jsonp:f}),window[f]=d.exceptionLogger(function(){g.apply(this,arguments);window[f]=void 0}),null!==b.timeout&&setTimeout(d.exceptionLogger(g),b.timeout));c=d.extend({format:"jsonp"},c);c=d.toQuery(c);a=a+(c.length?"?":"")+c;return b["return"]?
a:d.traits.cors&&!1!==d.cors(a)?!0:d.jsonp(a)},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,d,f=[];b=0;for(d=a.length;b<d;b++)f[b]=a[b];return f}},toQuery:function(a){var c,b="";for(c in a)null!==a[c]&&void 0!==a[c]&&(b+="\x26"+encodeURIComponent(c)+"\x3d"+encodeURIComponent(a[c]));return b.substr(1)},transmitsPII:function(a){return d.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return d.extend(d.createA(a),c).href},uniqid:function(){var a=
0;return function(c){return(c||"")+(new Date).getTime()+a++}}()});d.traits={basicCompatibility:!(d.browser.blackberry||d.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!(d.browser.ios&&d.browser.version&&(5>d.browser.version||5<d.browser.version)),jsRedirectSetsReferrer:d.browser.aol||!(d.browser.ie||d.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var e,
p,n,s=function(a){var c=a.previousSibling,b=a.nextSibling,g=["",a.textContent,""],f=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?c.data:"",g[2]=b&&3===b.nodeType?b.data:"",g=f.apply(this,g),""!==
g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(d.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:d.getActualHref(a),v:2},j.log("info",d.toQuery(a))))},k={};d.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};var l=d.exceptionLogger(function(){var a=!0===document.__v5k;document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),
this.initOptions(),d.exceptionLogger(d.bind(this.logException,this),!e.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}),w,r=1,v=[],u=function(){var a=[];w=null;d.each(v,function(c){var b,g=c[0],f=c[1],o=c[2],g=window.vglnk&&window.vglnk[g+"_plugin"],e=function(){if(b&&!o){var a=b,c=d.clone(d),g=f.key;a(f,c,n,function(){if(g){var a=d.toArray(arguments);a.unshift("custom",g);j.log.apply(this,a)}})}};g?(c="function"===d.type(g.run)?
g.run:null,b="function"===d.type(g.setup)?g.setup:null,f&&1===f.mode?(e(),delete f.mode):c&&(e(),c())):a.push(c)});v=a;0<v.length&&(w=setTimeout(d.exceptionLogger(u),Math.min(Math.max(Math.pow(2,++r),100),5E3)))},F=function(a,c){return function(){v.push([a,c,!0]);r=1;clearTimeout(w);u()}},y=d.canonicalizeHostname(document.location),z=d.generateNodeFilter({rels:["norewrite","noskim"],custom:function(a){var c,b="";try{c=a.hostname,b=a.protocol,c.charAt(0)}catch(g){return!0}""!==c&&(c=d.canonicalizeHostname(a));
return""===c||y===c||!b.match(/^https?:$/i)||e.norewrite[c]||!(e.rewrite_original||d.cache(a,"type"))}}),B=d.destructing(function(){var a={left:j.onClick,right:j.onContextmenu},c={left:d.noop,right:d.noop},b=d.traits.windowLevelHandlers?window:document,g=function(b){b=b||window.event;if((b=d.eventLink(b))&&!d.cache(b,"evented"))f(b,j.harmony(d.harmony.LINK_LEVEL_EVENTS)?a:c),d.cache(b,"evented",!0)},f=function(a,c){d.on(a,"click",d.bind(c.left,j));d.on(a,"contextmenu",d.bind(c.right,j))};d.on(b,"copy",
d.bind(j.onCopy,j));d.on(b,"mousedown",g);if(j.harmony(d.harmony.LINK_LEVEL_EVENTS))d.on("DOMReady",function(){d.each(document.links,function(a){d.on(a,"mousedown",g)})});(!d.traits.quirksMode||j.harmony(d.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&f(b,a)}),C,t=!1,x={},D=!1,E=[],A=function(a){if(void 0===a)return E;"function"===d.type(a)&&(E.push({id:d.uniqid(),fn:a}),D&&this.initLinks())};A(function(){D=!0});j={api:function(a,c,b){a=e.api_url+"/"+a;c=d.extend({cuid:e.cuid,key:e.key,drKey:e.key?null:e.dr_key,
loc:location.href,subId:e.sub_id,v:1},c);c.subId&&c.key!==e.key&&(c.subId=null);return d.request(a,c,b)},addEventListener:function(a,c){this.fire(a,c)},click:function(a,c){c=a.target||c;c=!c||c===window.name||"_top"===c&&window.top===window.self||"_parent"===c&&window.parent===window.self?"_self":c;var b,g,f;"_self"===c?f=window.self:d.traits.crossWindowCommunication&&d.traits.jsRedirectSetsReferrer?(g=window.open("",c),g.focus(),f=g):f=void 0;var o;if("_self"!==c&&(!d.traits.crossWindowCommunication||
!d.traits.jsRedirectSetsReferrer))o="go";else try{if(void 0===f.document)throw!0;o="jsonp"}catch(m){o="go"}b=d.destructing(d.bind(function(){e.time_click&&arguments.length&&this.logTime("clk");var b=d.toArray(arguments);b.unshift(a,f,c);this.onApiClick.apply(this,b)},this));d.cache(this,"link","string"===typeof a?a:d.getActualHref(a));if("string"===typeof a&&(a=d.createA(a,c),!this.processLink(a))||!e.enabled)return b();g=this.clickParams(a,o);this.logTime();e.log_context&&s(a);if("go"===o)this.redirect(this.api("click",
g,{"return":!0}),f,c);else if(f===window.self)this.api("click",g,{fn:b,timeout:e.click_timeout});else{if(d.contextIsAncestor(f))return this.redirect(d.getActualHref(a),f,c);b=d.exceptionLogger(b);setTimeout(function(){b()},e.click_timeout);f.document.open();f.callback=b;f.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+d.getActualHref(a)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+this.api("click",g,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');
f.document.close()}},clickParams:function(a,c){var b=d.extend(d.cache(a,"params"),{format:c,libId:e.library_id,out:d.getActualHref(a),ref:document.referrer||null,reaf:e.reaffiliate||null,title:document.title,txt:a.innerHTML});128<b.txt.length&&(b.txt=b.txt.replace(/<[^>]+>/g,""),b.txt=128<b.txt.length?b.txt.substr(0,125)+"...":b.txt);return b},enabled:function(){if(e.enabled&&p!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))e.enabled=!1;return e.enabled},expose:function(a,
c){if(c=c||this[a])"function"===typeof c?c=d.exceptionLogger(d.bind(c,this)):"object"===typeof c&&(c=d.clone(c)),n[a]||(n[a]=c)},fire:function(a,c){a=a.toLowerCase();var b=k[a]||{fired:!1,listeners:[]};"function"===typeof c?b.fired?c({type:a}):b.listeners.push(c):(b.fired=!0,d.each(b.listeners,function(c){"function"===typeof c&&c({type:a})}),b.listeners=[]);k[a]=b},handleRightClick:function(a,c){if(e.rewrite_modified&&a&&c)switch(c){case "setup":d.cache(a,"href")||d.cache(a,"href",a.href);a.href=
this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(d.exceptionLogger(d.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=d.cache(a,"href"),d.cache(a,"href",null)}},harmony:function(a){return e.harmony_level<=a},init:l,initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);n=p[h]=d.noop;this.expose("click");this.expose("link",function(a){"element"===d.type(a)&&a.href&&j.processLink(a)});
this.expose("$",d.clone(d));this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return j.registerProcessor.apply(j,arguments)});d.extend(n,n===window.vglnk?c:{})},initDRApi:function(){var a=!1;window.DrivingRevenue=d.exceptionLogger(d.destructing(d.bind(function(){a=!0;e.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));d.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=void 0}})},initLibEvents:function(){d.on(j);
d.ready(d.bind(function(){this.fire("DOMReady")},this))},initNamespace:function(){window.vglnk&&window.vglnk.key&&(h="vglnk");var a=window,c=h.split("."),b;for(h=c.pop();0<c.length;)b=c.shift(),a[b]=a[b]||{},a=a[b];p=a;n=p[h]=p[h]||{}},initOptions:function(){var a;this.initLegacyOptions();e=d.extend(this.publicOptions({api_url:"//api.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:d.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,
rewrite_modified:!1}),e,n,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{}},time_click:!1,time_ping:!1,js_testing:null});for(a in e)"_plugin"===a.substr(-7)&&delete e[a]},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(n[c[a]]=window[a],"vglnk_domain"===a&&
(n[c[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:d.bind(this.onApiClick,this),vl_disable:function(){e.enabled=!1}};for(a in c)window[a]=c[a]},initLinks:function(){d.each(d.toArray(document.links),d.bind(this.processLink,this))},initPlugins:function(a){for(var c in a)"object"===typeof a[c]&&!1!==a[c].enabled&&(v.push([c,a[c]]),1===a[c].mode&&this.expose("init_"+c,F(c,a[c])));u()},initProcessors:function(){this.registerProcessor(function(a){var c;c=d.createA(e.api_url);if("/api/click"===
a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=d.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,d.cache(a,"params",c))});this.registerProcessor(function(a){e.nofollow[a.href]&&!d.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&d.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target=
"_blank")})},isRewritable:function(a){return z(a,{ancestors:!1})},initEvents:B,log:function(a,c,b,g){var f,o=d.toQuery({nocache:d.uniqid()});f="pixel.gif";if("custom"===a)o+="\x26"+d.toQuery({key:c,type:b}),d.each("array"===d.type(g)?g:[g],function(a){d.each(["e","i","o"],function(c){delete a[c]});o+="\x26"+d.toQuery(a)});else{o+="\x26"+d.toQuery({key:e.key,drKey:e.key?null:e.dr_key});if("time"===a)f="time.gif",a={libId:e.library_id,time:b,type:c};else if("exception"===a)a={e:c,o:b};else if("info"===
a)a={i:c};else return;o+="\x26"+d.toQuery(a)}f=e.api_url+"/"+f+"?"+o;d.transmitsPII(f)||(d.createEl("img").src=f)},logException:function(a){if(e.debug){var c={link:d.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=d.extend(c,a);this.log("exception",a,d.toQuery(c))}},logTime:function(a){0===arguments.length?C=(new Date).getTime():this.log("time",a,(new Date).getTime()-C)},onApiClick:function(a,c,b,g,f){var o=g||d.getActualHref(a);g=d.bind(function(){this.redirect(o,
c,b)},this);"object"===typeof f&&(f.tracking||f.image)?(a=d.createEl(f.tracking?"iframe":"img",{src:f.tracking||f.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(a),setTimeout(d.exceptionLogger(g),f.timeout||e.hop_timeout)):g()},onApiPing:function(a,c,b,g,f,o){e.rewrite_original=!1;f=d.reformatKeys(f||{});var m,h;g=function(a){var c={},b=function(a){d.isArray(a)?c[a[0]]=a[1]:c[a]=1};d.isArray(a)&&d.each(a,b);return c};h=d.extend(e.plugins,f.plugins);e=d.extend(e,f);delete e.plugins;
e.library_id=a;e.click_timeout=c;e.time_ping&&this.logTime("png");e.js_testing&&d.jsonp(e.js_testing);d.extend(e.norewrite,g(b));d.extend(e.nofollow,g(o));for(m in e)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===d.type(e[m]))&&(d.on(j,m.toLowerCase().substr(2),d.bind(e[m],window)),delete e[m]);this.initPlugins(h);this.initLinks();this.initEvents();this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,b=a.which&&1===a.which||0===
a.button,g=d.eventLink(a);if(g&&this.isRewritable(g)&&!c&&b&&!d.isDefaultPrevented(a))return this.click(g),d.preventDefault(a)},onContextmenu:function(a){(a=d.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,c,b,g,f=[];if(window.getSelection){b=window.getSelection();a=0;for(c=b.rangeCount;a<c;a++){try{g=b.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(e){}0<g.length&&128>=g.length&&f.push(g)}}d.each(f,
function(a){j.log("info",d.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(e[a]=c);return e[a]},ping:function(){if(!t&&(e.key||e.dr_key)){var a={ref:document.referrer||null};t=!0;d.transmitsPII(this.api("ping",a,{"return":!0}))||(this.logTime(),this.api("ping",a,{fn:d.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var c=d.cache(a,"processors")||{};d.each(this.registerProcessor(),function(b){c[b.id]||
b.fn(a);c[b.id]=!0});d.cache(a,"processors",c);return a}},publicOptions:function(a){"object"===d.type(a)&&(x=a);return d.extend({},x)},redirect:function(a,c,b){!d.traits.crossWindowCommunication&&!c?(b=window.open(a,b),b.focus()):d.traits.jsRedirectSetsReferrer?setTimeout(d.exceptionLogger(function(){!c||c===window.self?window.location=a:d.contextIsAncestor(c)?c.location=a:c.location.replace(a)}),0):("_blank"===b&&(b=d.uniqid("win_")),b=d.createA(a,b),b.rel="norewrite",document.body.appendChild(b),
b.click(),b.parentNode.removeChild(b))},registerProcessor:A};j.init();try{delete window.vglnk_self}catch(b){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin=function(){var h;return{setup:function(j,d,e){h=e},run:function(){h.opt("rewrite_original",!0)}}}();window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(){var h;return{setup:function(j,d,e){h=e},run:function(){h.opt("rewrite_modified",!0)}}}();
window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(){var h,j,d={key:null},e={init:function(){h.each(this.getDRSearchForms(),function(d){if(!h.cache(d,"evented")){var n=e.getInput(d),s=function(){n.value||h.css(n,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};h.cache(d,"evented",!0);d.onsubmit=null;n.onfocus=null;n.onblur=null;h.on(n,"focus",function(){h.css(n,{"background-image":"none"})});h.on(n,"blur",s);s();h.on(d,"submit",function(h){e.onSubmit(h,d)})}})},getDRSearchForms:function(){var d=
[];h.each(document.getElementsByTagName("form"),function(h){e.getInput(h)&&h.id.match(/^DR-ebay-search(CSS|2)?$/i)&&d.push(h)});return d},getInput:function(d){return d.p||d.q2},onSubmit:function(p,n){p=p||window.event;var s="http://shop.ebay.com/i.html?"+h.toQuery({_nkw:e.getInput(n).value}),s=h.createA(s,"_blank");h.cache(s,"params",{key:d.key});j.click(s);return h.preventDefault(p)}};return{setup:function(e,n,s){h=n;j=s;d=h.extend(d,e)},run:function(){d.key&&(e.init(),h.on("DOMReady",h.bind(e.init,
e)))}}}();window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(){var h,j,d={level:null};return{setup:function(e,p,n){h=e;j=n;d=h.extend(d,p)},run:function(){var e=parseInt(d.level,10);isFinite(e)&&j.opt("harmony_level",e)}}}();window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(){var h,j,d={eb_campaign:5337208431,eb_cid:null,eb_gid:null,eb_group:null,eb_pct:20,eb_rotation:"711-53200-19255-0"},e=/(^|\.)ebay\.com$/,p=/(^|\.)rover\.ebay\.com$/,n={injectPixel:function(){if(d.eb_cid&&d.eb_campaign&&d.eb_rotation&&"number"===h.type(d.eb_gid)&&isFinite(d.eb_gid)&&0<=d.eb_gid){var e,k="//rover.ebay.com/roverimp/1/"+encodeURIComponent(d.eb_rotation)+"/1",l={campid:d.eb_campaign,ff19:d.eb_cid,ff20:d.eb_gid,mpt:Math.floor(99999999*Math.random()),
pub:5574713606,toolid:2E4};e=h.createEl("img",{src:k+"?"+h.toQuery(l)},{border:"none",height:0,width:0,position:"absolute",zIndex:-1});h.on("DOMReady",function(){document.body&&document.body.appendChild(e)})}},expandTruncatedUrl:function(d,e){var h;h=e.textContent||e.innerText;if(h&&(-1!==h.indexOf("...")||-1!==h.indexOf("\u2026"))){var n=h.split("...")[0].split("\u2026")[0],j=d.replace(/^http:\/\//i,"");h=n.length<d.length&&d.substr(0,n.length)===n||n.length<j.length&&j.substr(0,n.length)===n&&-1!==
h.indexOf("/")}else h=void 0;if(h){for(;h=e.firstChild;)e.removeChild(h);e.appendChild(document.createTextNode(d))}},shouldBeUnlinked:function(d,k){var l=h.canonicalizeHostname(d);return e.test(l)&&("inserted"===h.cache(k,"type")||!p.test(l))},unlink:function(d){var e,l,n=!0,j=h.getActualHref(d);if(this.shouldBeUnlinked(j,d)){e=document.createDocumentFragment();if(d.parentNode){for(;l=d.firstChild;)n=n&&3===l.nodeType,e.appendChild(l);n&&this.expandTruncatedUrl(j,e);d.parentNode.insertBefore(e,d);
d.parentNode.removeChild(d)}h.cache(d,"unlinked",!0)}}};return{setup:function(e,k,l){h=k;j=l;d=h.extend(d,e);null===d.eb_group&&(d.eb_group=d.eb_gid/10<d.eb_pct?1:0)},run:function(){n.injectPixel();1===d.eb_group&&j.registerProcessor(h.bind(n.unlink,n))}}}();window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(){var h,j,d,e={},p,n,s=null,k={},l={},w,r=0,v=0,u=0,F=0,y={setup:function(z,B,C,t){h=B;j=C;d=t;e=h.extend({cat:null,platform:null,api_url:h.updateUrl(j.opt("api_url"),{pathname:"/api/insert"}),key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0,lo:!1},z);if(!e.api_url||!e.key)y.run=h.noop;else{h=h.extend(h,{matches:window.vglnk.Sizzle.matchesSelector||
function(){return!0},select:window.vglnk.Sizzle||function(){return[]}});p={bbp:{id_finder:["li",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content, .postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^\x3d'body'], .post_inner .signature"},vb3:{id_finder:["td",/^td_post_(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},
vb4:{id_finder:["li",/^post_(\d+)$/],scope:".postbody .content, .postbody .signature, .post-content, ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}}[e.platform]||{};var x={timing:!1,data:e.link_phrases?!1:e.link_urls},D=function(a){var c=w.test(a.data),b=a.parentNode;if(c)for(var d=a,f,o,m,c=function(a,c){var b,d,i,f,g,o,m,k,j,n,q=function(c){j.parentNode.insertBefore(a,j);j.parentNode.removeChild(j);return c};j=h.createEl("span");a.parentNode.insertBefore(j,
a);j.appendChild(a);n=h.geometry(j);if(e.proximity||e.same_proximity)for(o in l)if((m=l[o].links)&&!(l[o]===c&&!e.same_proximity||l[o]!==c&&!e.proximity)){k=l[o]===c?Math.max(e.same_proximity,e.proximity):e.proximity;b=0;for(d=m.length;b<d;b++){g=m[b].segments;i=0;for(f=g.length;i<f;i++){var p=g[i].geometry,G=n,r=k,p=h.extend({},p);p.x1-=r;p.y1-=r;p.x2+=r;p.y2+=r;if(p.x1<G.x2&&p.x2>G.x1&&p.y1<G.y2&&p.y2>G.y1)return q(!1)}}}return q(!0)};d&&d.data&&Boolean(o=d.data.match(w));){f=o[0];m=o.slice(1).join("");
a=l[m.toLowerCase()];f=d.data.indexOf(f)+f.length-m.length;0<f&&(d=d.splitText(f));f=d.length<=m.length?null:d.splitText(m.length);m&&!a&&(a={url:m.match(/^https?:\/\//i)?m:"http://"+m,type:"U"});var k;if(k=m){var j=k=void 0;k=!a||!e.per_phrase||!a.count||a.count<e.per_phrase;j=!e.per_page||r<e.per_page;k=k&&j&&c(d,a)}if(k&&(k=a,j=void 0,j=h.createEl("a"),j.innerHTML=m.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),j.className="vglnk",h.cache(j,"type","inserted"),h.cache(j,"phrase",
m),e.ui&&(j.title="Link added by VigLink"),n.initLink(j,k),m=j,!h.cache(m,"unlinked"))){"U"===a.type?F++:"L"===a.type.toUpperCase()?v++:u++;b.insertBefore(m,d);b.removeChild(d);var d=a,p=j=k=void 0,t=void 0,q={el:m,segments:[]};m=m.getElementsByTagName("span");var s={els:[]};k=0;for(j=m.length;k<j;k++)p=m[k],void 0===t||p.offsetTop===t.offsetTop?s.els.push(p):(q.segments.push(s),s={els:[p]}),t=p;s.geometry=h.geometry.apply(h,s.els);q.segments.push(s);d.links=d.links||[];d.links.push(q);a.count++;
r++}d=f}},E=h.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return h.matches(a,"a[href]")}}),A=function(a){var c;if(a){if(E(a,{ancestors:!1,self:!0}))for(c=a.firstChild;c;)a=c.nextSibling,1===c.nodeType?A(c):3===c.nodeType&&D(c),c=a}else h.each(h.select(e.scope),function(a){E(a,{ancestors:!0,self:!1})&&A(a)})},b=h.generateNodeFilter({classes:["nooptimize"],
rels:["nooptimize"],custom:function(a,c){return c?Boolean(h.cache(a,"type")):!1}});n={addPhrasesToMatcher:function(a){var c="";"regexp"===h.type(a)?c=a.source:"array"===h.type(a)&&(c="(?:^|[\\s\"'\\(])("+h.map(a,h.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==c&&(w=RegExp(w?"(?:"+c+"|"+w.source+")":c,"i"))},focusLink:function(a){a.id||(a.id=h.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(a){h.request(e.api_url,h.extend(n.getPartnerParams(),
{cat:e.cat,key:e.key,mode:e.mode,pt:e.platform,ps:e.product_source,i:a?a.join("|"):null,u:location.href,type:e.type,lo:e.lo}),{fn:h.bind(n.onInsertApi,n)})},getPartnerParams:function(){var a,c,b=j.opt("partner"),d={};for(a in b)break;if(a)for(c in b[a])d[a+"_"+c]=b[a][c];return d},getPostIDs:function(){var a=[],c=p?p.id_finder:null;c&&h.each(h.select(c[0]),function(b){var d=c[2]||"id";(b=b[d]?b[d].match(c[1]):null)&&a.push(b[1])});return a.length?a:null},initLink:function(a,c,b){if(b=e.link_target||
b)a.target=b;a.rel="nofollow";a.href||(a.href=c.url);h.cache(a,"params",{exp:s,key:e.key,mid:c.mid,type:c.type||null});h.cache(a,"href",a.href);j.link(a)},insertLinks:function(a){x=h.extend(x,a);x.timing&&(x.data&&w)&&(A(),n.log())},loadPhrases:function(a){var c,b,d,f=[];c=0;for(b=a.length;c<b;c++)d=a[c],d.phrase&&d.url&&(d.phrase=d.phrase.toLowerCase(),l[d.phrase]||(f.push(d.phrase),l[d.phrase]={count:l[d.phrase]?l[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||""}));0<f.length&&
this.addPhrasesToMatcher(f);this.insertLinks({data:!0})},log:function(){var a,b,i={heavy:[],lite:[]},g=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(a in l)b=parseInt(l[a].count,10),0<b&&(b=[b,a.replace(/\|/g,"%7C")].join(),i["L"===l[a].type.toUpperCase()?"lite":"heavy"].push(b));i.lite.sort(g);i.heavy.sort(g);d("insert",[{ct:r,cl:v,ch:u,cu:F,exp:s},{pl:i.lite.join("|")},{ph:i.heavy.join("|")}])},onInsertApi:function(a){"object"===h.type(a)&&(s=a.exp,a.results&&this.loadPhrases(a.results),
e.lo&&"object"===h.type(a.links)&&(k=a.links,j.registerProcessor(h.bind(this.optimizeLink,n))))},optimizeLink:function(a){var c=k[a.href];if(c&&b(a)){var d=a.textContent||a.innerText,g;if(!(g=a.href===d)){g=h.canonicalizeHostname(a);var f=h.createEl("a",{href:d});h.canonicalizeHostname(f)===g?(g=h.fromQuery(a.search),g=h.find(g,function(a){return a===d})):g=!1}if(g){for(;g=a.firstChild;)a.removeChild(g);a.appendChild(document.createTextNode(c))}h.cache(a,"params",{type:"LO"});a.href=c}},setup:function(){var a=
h.bind(function(){this.getPhrases(this.getPostIDs())},this);e.scope=e.scope||p.scope||"body";e.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"));if(e.link_phrases)if(!e.platform||
"full"===e.platform)a();else h.on("DOMReady",a)}};n.setup()}},run:function(){h.on("DOMReady",function(){n.insertLinks({timing:!0})})}};return y}();
(function(){function h(b,a,c,d,g,f){g=0;for(var e=d.length;g<e;g++){var m=d[g];if(m){for(var h=!1,m=m[b];m;){if(m.sizcache===c){h=d[m.sizset];break}1===m.nodeType&&!f&&(m.sizcache=c,m.sizset=g);if(m.nodeName.toLowerCase()===a){h=m;break}m=m[b]}d[g]=h}}}function j(b,a,c,d,g,f){g=0;for(var e=d.length;g<e;g++){var h=d[g];if(h){for(var l=!1,h=h[b];h;){if(h.sizcache===c){l=d[h.sizset];break}if(1===h.nodeType)if(f||(h.sizcache=c,h.sizset=g),"string"!==typeof a){if(h===a){l=!0;break}}else if(0<k.filter(a,
[h]).length){l=h;break}h=h[b]}d[g]=l}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,p=Object.prototype.toString,n=!1,s=!0;[0,0].sort(function(){s=!1;return 0});var k=function(b,a,c,i){c=c||[];var g=a=a||document;if(1!==a.nodeType&&9!==a.nodeType)return[];if(!b||"string"!==typeof b)return c;var f,e,h,j,n,r=!0,s=k.isXML(a),q=[],t=b;do if(d.exec(""),f=d.exec(t))if(t=f[3],q.push(f[1]),f[2]){j=f[3];break}while(f);
if(1<q.length&&w.exec(b))if(2===q.length&&l.relative[q[0]])e=A(q[0]+q[1],a);else for(e=l.relative[q[0]]?[a]:k(q.shift(),a);q.length;)b=q.shift(),l.relative[b]&&(b+=q.shift()),e=A(b,e);else if(!i&&(1<q.length&&9===a.nodeType&&!s&&l.match.ID.test(q[0])&&!l.match.ID.test(q[q.length-1]))&&(f=k.find(q.shift(),a,s),a=f.expr?k.filter(f.expr,f.set)[0]:f.set[0]),a){f=i?{expr:q.pop(),set:u(i)}:k.find(q.pop(),1===q.length&&("~"===q[0]||"+"===q[0])&&a.parentNode?a.parentNode:a,s);e=f.expr?k.filter(f.expr,f.set):
f.set;for(0<q.length?h=u(e):r=!1;q.length;)f=n=q.pop(),l.relative[n]?f=q.pop():n="",null==f&&(f=a),l.relative[n](h,f,s)}else h=[];h||(h=e);h||k.error(n||b);if("[object Array]"===p.call(h))if(r)if(a&&1===a.nodeType)for(b=0;null!=h[b];b++)h[b]&&(!0===h[b]||1===h[b].nodeType&&k.contains(a,h[b]))&&c.push(e[b]);else for(b=0;null!=h[b];b++)h[b]&&1===h[b].nodeType&&c.push(e[b]);else c.push.apply(c,h);else u(h,c);j&&(k(j,g,c,i),k.uniqueSort(c));return c};k.uniqueSort=function(b){if(y&&(n=s,b.sort(y),n))for(var a=
1;a<b.length;a++)b[a]===b[a-1]&&b.splice(a--,1);return b};k.matches=function(b,a){return k(b,null,null,a)};k.matchesSelector=function(b,a){return 0<k(a,null,null,[b]).length};k.find=function(b,a,c){var d;if(!b)return[];for(var g=0,f=l.order.length;g<f;g++){var e,h=l.order[g];if(e=l.leftMatch[h].exec(b)){var k=e[1];e.splice(1,1);if("\\"!==k.substr(k.length-1)&&(e[1]=(e[1]||"").replace(/\\/g,""),d=l.find[h](e,a,c),null!=d)){b=b.replace(l.match[h],"");break}}}d||(d="undefined"!==typeof a.getElementsByTagName?
a.getElementsByTagName("*"):[]);return{set:d,expr:b}};k.filter=function(b,a,c,d){for(var g,f,e=b,h=[],j=a,n=a&&a[0]&&k.isXML(a[0]);b&&a.length;){for(var p in l.filter)if(null!=(g=l.leftMatch[p].exec(b))&&g[2]){var r,q,s=l.filter[p];q=g[1];f=!1;g.splice(1,1);if("\\"!==q.substr(q.length-1)){j===h&&(h=[]);if(l.preFilter[p])if(g=l.preFilter[p](g,j,c,h,d,n)){if(!0===g)continue}else f=r=!0;if(g)for(var t=0;null!=(q=j[t]);t++)if(q){r=s(q,g,t,j);var u=d^!!r;c&&null!=r?u?f=!0:j[t]=!1:u&&(h.push(q),f=!0)}if(void 0!==
r){c||(j=h);b=b.replace(l.match[p],"");if(!f)return[];break}}}if(b===e)if(null==f)k.error(b);else break;e=b}return j};k.error=function(b){throw"Syntax error, unrecognized expression: "+b;};var l=k.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(b){return b.getAttribute("href")}},relative:{"+":function(b,a){var c="string"===typeof a,d=c&&!/\W/.test(a),c=c&&!d;d&&(a=a.toLowerCase());for(var d=0,g=
b.length,f;d<g;d++)if(f=b[d]){for(;(f=f.previousSibling)&&1!==f.nodeType;);b[d]=c||f&&f.nodeName.toLowerCase()===a?f||!1:f===a}c&&k.filter(a,b,!0)},"\x3e":function(b,a){var c,d="string"===typeof a,g=0,f=b.length;if(d&&!/\W/.test(a))for(a=a.toLowerCase();g<f;g++){if(c=b[g])c=c.parentNode,b[g]=c.nodeName.toLowerCase()===a?c:!1}else{for(;g<f;g++)(c=b[g])&&(b[g]=d?c.parentNode:c.parentNode===a);d&&k.filter(a,b,!0)}},"":function(b,a,c){var d,g=e++,f=j;"string"===typeof a&&!/\W/.test(a)&&(d=a=a.toLowerCase(),
f=h);f("parentNode",a,g,b,d,c)},"~":function(b,a,c){var d,g=e++,f=j;"string"===typeof a&&!/\W/.test(a)&&(d=a=a.toLowerCase(),f=h);f("previousSibling",a,g,b,d,c)}},find:{ID:function(b,a,c){if("undefined"!==typeof a.getElementById&&!c)return(b=a.getElementById(b[1]))&&b.parentNode?[b]:[]},NAME:function(b,a){if("undefined"!==typeof a.getElementsByName){for(var c=[],d=a.getElementsByName(b[1]),g=0,f=d.length;g<f;g++)d[g].getAttribute("name")===b[1]&&c.push(d[g]);return 0===c.length?null:c}},TAG:function(b,
a){if("undefined"!==typeof a.getElementsByTagName)return a.getElementsByTagName(b[1])}},preFilter:{CLASS:function(b,a,c,d,g,f){b=" "+b[1].replace(/\\/g,"")+" ";if(f)return b;f=0;for(var e;null!=(e=a[f]);f++)e&&(g^(e.className&&0<=(" "+e.className+" ").replace(/[\t\n\r]/g," ").indexOf(b))?c||d.push(e):c&&(a[f]=!1));return!1},ID:function(b){return b[1].replace(/\\/g,"")},TAG:function(b){return b[1].toLowerCase()},CHILD:function(b){if("nth"===b[1]){b[2]||k.error(b[0]);b[2]=b[2].replace(/^\+|\s*/g,"");
var a=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===b[2]&&"2n"||"odd"===b[2]&&"2n+1"||!/\D/.test(b[2])&&"0n+"+b[2]||b[2]);b[2]=a[1]+(a[2]||1)-0;b[3]=a[3]-0}else b[2]&&k.error(b[0]);b[0]=e++;return b},ATTR:function(b,a,c,d,g,f){a=b[1]=b[1].replace(/\\/g,"");!f&&l.attrMap[a]&&(b[1]=l.attrMap[a]);b[4]=(b[4]||b[5]||"").replace(/\\/g,"");"~\x3d"===b[2]&&(b[4]=" "+b[4]+" ");return b},PSEUDO:function(b,a,c,e,g){if("not"===b[1])if(1<(d.exec(b[3])||"").length||/^\w/.test(b[3]))b[3]=k(b[3],null,null,a);else return b=
k.filter(b[3],a,c,1^g),c||e.push.apply(e,b),!1;else if(l.match.POS.test(b[0])||l.match.CHILD.test(b[0]))return!0;return b},POS:function(b){b.unshift(!0);return b}},filters:{enabled:function(b){return!1===b.disabled&&"hidden"!==b.type},disabled:function(b){return!0===b.disabled},checked:function(b){return!0===b.checked},selected:function(b){return!0===b.selected},parent:function(b){return!!b.firstChild},empty:function(b){return!b.firstChild},has:function(b,a,c){return!!k(c[3],b).length},header:function(b){return/h\d/i.test(b.nodeName)},
text:function(b){return"text"===b.type},radio:function(b){return"radio"===b.type},checkbox:function(b){return"checkbox"===b.type},file:function(b){return"file"===b.type},password:function(b){return"password"===b.type},submit:function(b){return"submit"===b.type},image:function(b){return"image"===b.type},reset:function(b){return"reset"===b.type},button:function(b){return"button"===b.type||"button"===b.nodeName.toLowerCase()},input:function(b){return/input|select|textarea|button/i.test(b.nodeName)}},
setFilters:{first:function(b,a){return 0===a},last:function(b,a,c,d){return a===d.length-1},even:function(b,a){return 0===a%2},odd:function(b,a){return 1===a%2},lt:function(b,a,c){return a<c[3]-0},gt:function(b,a,c){return a>c[3]-0},nth:function(b,a,c){return c[3]-0===a},eq:function(b,a,c){return c[3]-0===a}},filter:{PSEUDO:function(b,a,c,d){var g=a[1],f=l.filters[g];if(f)return f(b,c,a,d);if("contains"===g)return 0<=(b.textContent||b.innerText||k.getText([b])||"").indexOf(a[3]);if("not"===g){a=a[3];
c=0;for(d=a.length;c<d;c++)if(a[c]===b)return!1;return!0}k.error(g)},CHILD:function(b,a){var c=a[1],d=b;switch(c){case "only":case "first":for(;d=d.previousSibling;)if(1===d.nodeType)return!1;if("first"===c)return!0;d=b;case "last":for(;d=d.nextSibling;)if(1===d.nodeType)return!1;return!0;case "nth":var c=a[2],g=a[3];if(1===c&&0===g)return!0;var f=a[0],e=b.parentNode;if(e&&(e.sizcache!==f||!b.nodeIndex)){for(var h=0,d=e.firstChild;d;d=d.nextSibling)1===d.nodeType&&(d.nodeIndex=++h);e.sizcache=f}d=
b.nodeIndex-g;return 0===c?0===d:0===d%c&&0<=d/c}},ID:function(b,a){return 1===b.nodeType&&b.getAttribute("id")===a},TAG:function(b,a){return"*"===a&&1===b.nodeType||b.nodeName.toLowerCase()===a},CLASS:function(b,a){return-1<(" "+(b.className||b.getAttribute("class"))+" ").indexOf(a)},ATTR:function(b,a){var c=a[1],c=l.attrHandle[c]?l.attrHandle[c](b):null!=b[c]?b[c]:b.getAttribute(c),d=c+"",g=a[2],f=a[4];return null==c?"!\x3d"===g:"\x3d"===g?d===f:"*\x3d"===g?0<=d.indexOf(f):"~\x3d"===g?0<=(" "+d+
" ").indexOf(f):!f?d&&!1!==c:"!\x3d"===g?d!==f:"^\x3d"===g?0===d.indexOf(f):"$\x3d"===g?d.substr(d.length-f.length)===f:"|\x3d"===g?d===f||d.substr(0,f.length+1)===f+"-":!1},POS:function(b,a,c,d){var g=l.setFilters[a[2]];if(g)return g(b,c,a,d)}}},w=l.match.POS,r=function(b,a){return"\\"+(a-0+1)},v;for(v in l.match)l.match[v]=RegExp(l.match[v].source+/(?![^\[]*\])(?![^\(]*\))/.source),l.leftMatch[v]=RegExp(/(^(?:.|\r|\n)*?)/.source+l.match[v].source.replace(/\\(\d+)/g,r));var u=function(b,a){b=Array.prototype.slice.call(b,
0);return a?(a.push.apply(a,b),a):b};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(F){u=function(b,a){var c=0,d=a||[];if("[object Array]"===p.call(b))Array.prototype.push.apply(d,b);else if("number"===typeof b.length)for(var g=b.length;c<g;c++)d.push(b[c]);else for(;b[c];c++)d.push(b[c]);return d}}var y,z;document.documentElement.compareDocumentPosition?y=function(b,a){return b===a?(n=!0,0):!b.compareDocumentPosition||!a.compareDocumentPosition?b.compareDocumentPosition?
-1:1:b.compareDocumentPosition(a)&4?-1:1}:(y=function(b,a){var c,d,g=[],f=[];c=b.parentNode;d=a.parentNode;var e=c;if(b===a)return n=!0,0;if(c===d)return z(b,a);if(c){if(!d)return 1}else return-1;for(;e;)g.unshift(e),e=e.parentNode;for(e=d;e;)f.unshift(e),e=e.parentNode;c=g.length;d=f.length;for(e=0;e<c&&e<d;e++)if(g[e]!==f[e])return z(g[e],f[e]);return e===c?z(b,f[e],-1):z(g[e],a,1)},z=function(b,a,c){if(b===a)return c;for(b=b.nextSibling;b;){if(b===a)return-1;b=b.nextSibling}return 1});k.getText=
function(b){for(var a="",c,d=0;b[d];d++)c=b[d],3===c.nodeType||4===c.nodeType?a+=c.nodeValue:8!==c.nodeType&&(a+=k.getText(c.childNodes));return a};r=document.createElement("div");v="script"+(new Date).getTime();var B=document.documentElement;r.innerHTML="\x3ca name\x3d'"+v+"'/\x3e";B.insertBefore(r,B.firstChild);document.getElementById(v)&&(l.find.ID=function(b,a,c){if("undefined"!==typeof a.getElementById&&!c)return(a=a.getElementById(b[1]))?a.id===b[1]||"undefined"!==typeof a.getAttributeNode&&
a.getAttributeNode("id").nodeValue===b[1]?[a]:void 0:[]},l.filter.ID=function(b,a){var c="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id");return 1===b.nodeType&&c&&c.nodeValue===a});B.removeChild(r);B=r=null;r=document.createElement("div");r.appendChild(document.createComment(""));0<r.getElementsByTagName("*").length&&(l.find.TAG=function(b,a){var c=a.getElementsByTagName(b[1]);if("*"===b[1]){for(var d=[],e=0;c[e];e++)1===c[e].nodeType&&d.push(c[e]);c=d}return c});r.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
r.firstChild&&("undefined"!==typeof r.firstChild.getAttribute&&"#"!==r.firstChild.getAttribute("href"))&&(l.attrHandle.href=function(b){return b.getAttribute("href",2)});r=null;if(document.querySelectorAll){var C=k,r=document.createElement("div");r.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(r.querySelectorAll&&0===r.querySelectorAll(".TEST").length)){var k=function(b,a,c,d){a=a||document;if(!d&&!k.isXML(a)){var e=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(b);if(e&&(1===a.nodeType||9===a.nodeType)){if(e[1])return u(a.getElementsByTagName(b),
c);if(e[2]&&l.find.CLASS&&a.getElementsByClassName)return u(a.getElementsByClassName(e[2]),c)}if(9===a.nodeType){if("body"===b&&a.body)return u([a.body],c);if(e&&e[3]){var f=a.getElementById(e[3]);if(f&&f.parentNode){if(f.id===e[3])return u([f],c)}else return u([],c)}try{return u(a.querySelectorAll(b),c)}catch(h){}}else if(1===a.nodeType&&"object"!==a.nodeName.toLowerCase()){var f=(e=a.getAttribute("id"))||"__sizzle__",j=a.parentNode,n=/^\s*[+~]/.test(b);e?f=f.replace(/'/g,"\\$\x26"):a.setAttribute("id",
f);n&&j&&(a=a.parentNode);try{if(!n||j)return u(a.querySelectorAll("[id\x3d'"+f+"'] "+b),c)}catch(p){}finally{e||a.removeAttribute("id")}}}return C(b,a,c,d)},t;for(t in C)k[t]=C[t];r=null}}t=document.documentElement;var x=t.matchesSelector||t.mozMatchesSelector||t.webkitMatchesSelector||t.msMatchesSelector,D=!1;try{x.call(document.documentElement,"[test!\x3d'']:sizzle")}catch(E){D=!0}x&&(k.matchesSelector=function(b,a){a=a.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!k.isXML(b))try{if(D||!l.match.PSEUDO.test(a)&&
!/!=/.test(a))return x.call(b,a)}catch(c){}return 0<k(a,null,null,[b]).length});t=document.createElement("div");t.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";t.getElementsByClassName&&0!==t.getElementsByClassName("e").length&&(t.lastChild.className="e",1!==t.getElementsByClassName("e").length&&(l.order.splice(1,0,"CLASS"),l.find.CLASS=function(b,a,c){if("undefined"!==typeof a.getElementsByClassName&&!c)return a.getElementsByClassName(b[1])},t=null));
k.contains=document.documentElement.contains?function(b,a){return b!==a&&(b.contains?b.contains(a):!0)}:document.documentElement.compareDocumentPosition?function(b,a){return!!(b.compareDocumentPosition(a)&16)}:function(){return!1};k.isXML=function(b){return(b=(b?b.ownerDocument||b:0).documentElement)?"HTML"!==b.nodeName:!1};var A=function(b,a){for(var c,d=[],e="",f=a.nodeType?[a]:a;c=l.match.PSEUDO.exec(b);)e+=c[0],b=b.replace(l.match.PSEUDO,"");b=l.relative[b]?b+"*":b;c=0;for(var h=f.length;c<h;c++)k(b,
f[c],d);return k.filter(e,d)};window.vglnk.Sizzle=k})();